FORMAT: 1A

# ROOT

# API Root [/]

## Doc and API end points [GET]

+ Response 200 (application/json)

        {
            "dosc": "/docs",
            "queries_url": "/api/queries",
            "sql_url": "/api/sql"
        }

# Group Queries

# Queries [/api/queries]

## List all queries [GET]
+ Response 200 (application/json)

        { "queries":
            [
                {
                    "id": 1,
                    "uri": "/api/queries/1",
                    "name": "Ventas mensuales"
                },
                {
                    "id": 2,
                    "uri": "/api/queries/2",
                    "name": "Ventas perdidas"
                },
                {
                    "id": 3,
                    "uri": "/api/queries/3",
                    "name": "Lista de clientes"
                }
            ]
        }

## Add new quiry [POST]
Request values description:
+ name (required, string) - Query name
+ description (string) - Short description of query
+ params (array[object]) - List of params
+ query (required, string)

+ Relation: create

+ Request (application/json)

        {
            "name": "New query",
            "description": "A short description of query",
            "params": [
                {
                    "name": "start_date",
                    "type": "date",
                    "default": "Default value"
                },
                {
                    "name": "end_date",
                    "type": "date",
                    "default": "Default value"
                }
            ],
            "query": "select * from table"
        }

+ Response 201

    + Headers

            Location: /queries/15

## Get parametes of Query [GET /api/queries/{query_id}]
Return the list of parameters

+ Parameters
    + query_id: 1 (required, number) - An unique identifier of the query.

+ Response 200 (application/json)

        {
            "status": "success",
            "data":{
                "name": "Ventas mensuales",
                "uri": "/api/queries/15/data"
                "params": [
                    {
                        "name": "start_date",
                        "type": "date",
                        "description": "Fecha de inicio de la consulta"
                    },
                    {
                        "name": "end_date",
                        "type": "date",
                        "description": "Fecha de cierre de la consulta"
                    }
                ]
            }
        }

## Modifi a storage query [PATCH /api/queries/{query_id}]
+ Parameters
    + query_id: 1 (number) - An unique identifier of the message.

+ Request (application/json)

        {
            "name": "New query",
            "description": "A short description of query",
            "params": [
                {
                    "name": "start_date",
                    "value": "date"
                },
                {
                    "name": "end_date",
                    "type": "value",
                }
            ],
            "query": "select * from table"
        }

+ Response 200 (application/json)

        {
            "status": "success"
        }

## Delete a storage query [DELETE /api/queries/{query_id}]
+ Parameters
    + query_id: 1 (number) - An unique identifier of the message.

+ Response 200 (application/json)

        {
            "status": "success"
        }

## Execute the senctes [GET /api/queries/{query_id}/data]

+ params (array[object]) - List of params

+ Parameters
    + query_id: 1 (required, number) - An unique identifier of the query.

+ Request (application/json)

        {
            "params": [
                {
                    "name": "start_date",
                    "value": "date"
                },
                {
                    "name": "end_date",
                    "type": "value",
                }
            ]
        }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": { array[object] }
        }


# Group SQL

## SQL [/api/sql]

## Execute custom SQL query [GET]
+ Request (application/json)

        { "query": "SELECT * FROM table" }

+ Response 200 (application/json)

        {
            "status": "success",
            "data": { array[object] }
        }
